"""empty message

Revision ID: b934a8d95555
Revises: 9e51900888be
Create Date: 2021-08-01 18:28:26.646910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b934a8d95555'
down_revision = '9e51900888be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drinks',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=True),
                    sa.Column('image_url', sa.String(
                        length=50), nullable=True),
                    sa.Column('abv', sa.String(length=50), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('type', sa.String(length=50), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('beers', sa.Column('malt', sa.Text(), nullable=True))
    op.add_column('beers', sa.Column('hops', sa.String(), nullable=True))
    op.add_column('beers', sa.Column('yeast', sa.Text(), nullable=True))
    op.add_column('beers', sa.Column(
        'first_brewed', sa.String(), nullable=True))
    op.create_foreign_key(None, 'beers', 'drinks', ['id'], ['id'])
    op.drop_column('beers', 'beerObj')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beers', sa.Column('beerObj', postgresql.JSON(
        astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'beers', type_='foreignkey')
    op.drop_column('beers', 'first_brewed')
    op.drop_column('beers', 'yeast')
    op.drop_column('beers', 'hops')
    op.drop_column('beers', 'malt')
    op.drop_table('drinks')
    # ### end Alembic commands ###
