"""decimal

Revision ID: 038f0aea3d32
Revises: fb35aa701ec4
Create Date: 2021-09-02 15:11:16.064343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '038f0aea3d32'
down_revision = 'fb35aa701ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drinks', 'abv')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drinks', sa.Column('abv', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
