"""remove image url

Revision ID: 3e74272e475b
Revises: bf17d307b224
Create Date: 2021-08-31 14:21:07.378196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e74272e475b'
down_revision = 'bf17d307b224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drinks', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drinks', sa.Column('image_url', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
