"""empty message

Revision ID: 4af27c7ab57f
Revises: b934a8d95555
Create Date: 2021-08-03 15:28:57.688102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af27c7ab57f'
down_revision = 'b934a8d95555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'name')
    # ### end Alembic commands ###
