"""added decimal

Revision ID: d1155f0393e6
Revises: 038f0aea3d32
Create Date: 2021-09-02 15:12:02.548554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1155f0393e6'
down_revision = '038f0aea3d32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('drinks', sa.Column(
        'abv', sa.Float(precision=2)))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drinks', 'abv')
    # ### end Alembic commands ###
