"""change image url

Revision ID: fb35aa701ec4
Revises: 3e74272e475b
Create Date: 2021-08-31 14:21:29.872833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb35aa701ec4'
down_revision = '3e74272e475b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drinks', sa.Column('image_url', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drinks', 'image_url')
    # ### end Alembic commands ###
